language: java
jdk:
 - openjdk8
dist: xenial
addons:
  sonarcloud:
    organization: "unimibsoftengcourse2021"
    token:
      secure: "256feed6f3230b29b251400ae6ef9b4ee69a0daf" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=UnimibSoftEngCourse2021_travis-exercise-apcortez