language: java
dist: xenial
addons:
  sonarcloud:
    organization: "unimibsoftengcourse2021"
    token: ${SONAR_TOKEN} # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn install sonar:sonar -Dsonar.projectKey=UnimibSoftEngCourse2021_travis-exercise-apcortez